name: Plugin Tests PHP Matrix

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
    name: PHP ${{ matrix.php-versions }}
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mautic_test
          MYSQL_USER: mautic
          MYSQL_PASSWORD: mautic
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
          coverage: none

      - name: Download Mautic
        run: |
          git clone https://github.com/mautic/mautic.git mautic5.2
          cd mautic5.2
          git checkout 5.2.0

      - name: Install Mautic dependencies
        working-directory: ./mautic5.2
        run: |
          composer validate
          composer install --no-interaction --no-progress

      - name: Move plugin to Mautic plugins directory
        run: |
          mkdir -p mautic5.2/plugins/LenonLeiteFilterValidEmailRecipientBundle
          mv $(ls -A | grep -v "mautic5.2") mautic5.2/plugins/LenonLeiteFilterValidEmailRecipientBundle/

      - name: Run plugin tests
        working-directory: ./mautic5.2
        env:
          MAUTIC_DB_HOST: 127.0.0.1
          MAUTIC_DB_PORT: 3306
          MAUTIC_DB_USER: mautic
          MAUTIC_DB_PASSWORD: mautic
          MAUTIC_DB_NAME: mautic_test
        run: |
          composer test -- --filter LenonLeiteFilterValidEmailRecipientBundle