name: Plugin Tests PHP Matrix

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
    name: PHP ${{ matrix.php-versions }}
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mautic_test
          MYSQL_USER: mautic
          MYSQL_PASSWORD: mautic
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
          coverage: none

      - name: Download Mautic
        run: |
          git clone https://github.com/mautic/mautic.git mautic5.2
          cd mautic5.2
          git checkout 5.2.0

      - name: Configure Mautic Test Environment
        working-directory: ./mautic5.2
        run: |
          cp .env .env.test.local
          sed -i 's,DATABASE_URL=.*,DATABASE_URL="mysql://mautic:mautic@127.0.0.1:3306/mautic_test?serverVersion=8.0.37\&charset=utf8mb4",g' .env.test.local

      - name: Install Mautic dependencies
        working-directory: ./mautic5.2
        run: |
          composer validate
          composer install --no-interaction --no-progress

      - name: Move plugin to Mautic plugins directory
        run: |
          mkdir -p mautic5.2/plugins/LenonLeiteFilterValidEmailRecipientBundle
          mv $(ls -A | grep -v "mautic5.2") mautic5.2/plugins/LenonLeiteFilterValidEmailRecipientBundle/

      - name: Setup test database
        working-directory: ./mautic5.2
        env:
          APP_ENV: test
          DATABASE_URL: "mysql://mautic:mautic@127.0.0.1:3306/mautic_test?serverVersion=8.0.37&charset=utf8mb4"
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Run plugin tests
        working-directory: ./mautic5.2
        env:
          APP_ENV: test
          DATABASE_URL: "mysql://mautic:mautic@127.0.0.1:3306/mautic_test?serverVersion=8.0.37&charset=utf8mb4"
        run: |
          composer test -- --filter LenonLeiteFilterValidEmailRecipientBundle